# coding: utf-8

"""
    Analysis

    Analyse content using Linked Data and Knowledge Graphs.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from analysis_client.api.analyses_api import AnalysesApi


class TestAnalysesApi(unittest.TestCase):
    """AnalysesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnalysesApi()

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Create
        """
        pass


if __name__ == '__main__':
    unittest.main()
